-- 
CREATE DATABASE appdb;

CREATE USER appuser WITH PASSWORD 'secret';
CREATE USER migrateuser WITH PASSWORD 'migrate_secret';

GRANT CONNECT ON DATABASE appdb TO appuser;
GRANT CONNECT ON DATABASE appdb TO migrateuser;

\c appdb

GRANT USAGE ON SCHEMA public TO appuser;
GRANT USAGE, CREATE ON SCHEMA public TO migrateuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO appuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO appuser;

REVOKE CREATE ON SCHEMA public FROM appuser;

\q